services:
  testtask.api:
    image: testtask.api
    environment:
      - ConnectionStrings__TestTaskDbContext=${ConnectionStrings__TestTaskDbContext}
    build:
      context: .
      dockerfile: TestTask.Api/Dockerfile
    depends_on:
      testtask.db:
        condition: service_healthy
      
      
  testtask.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    postgres-data:
